# Generated by Django 4.0.6 on 2022-09-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docket',
            fields=[
                ('docket_number', models.TextField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(null=True)),
                ('varietal', models.TextField()),
                ('vineyard', models.TextField()),
                ('block', models.TextField()),
                ('number_of_bins', models.IntegerField(null=True)),
                ('total_weight_kg', models.IntegerField(null=True)),
                ('tare_weight_kg', models.IntegerField(null=True)),
                ('actual_volume', models.IntegerField(null=True)),
                ('order_id', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('bricks', models.IntegerField()),
                ('ph', models.IntegerField()),
                ('tartaric_acid', models.IntegerField()),
                ('yan', models.IntegerField()),
                ('dap_needs', models.IntegerField()),
                ('comments', models.TextField()),
                ('temperature', models.IntegerField()),
                ('dockets', models.ManyToManyField(to='dockets.docket')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('vessel_id', models.IntegerField()),
                ('dockets', models.ManyToManyField(to='dockets.docket')),
            ],
        ),
    ]
