# Generated by Django 4.1.1 on 2022-11-21 02:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseChoiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.TextField(unique=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Constants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.TextField(unique=True)),
                ('data_type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CrushOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vintage', models.IntegerField(null=True)),
                ('crush_type', models.TextField(null=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 20, 18, 28, 14, 341516))),
            ],
        ),
        migrations.CreateModel(
            name='CrushOrderDocketMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('units', models.TextField(null=True)),
                ('crush_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crush_order_docket_mappings', to='apps.crushorder')),
            ],
        ),
        migrations.CreateModel(
            name='CrushOrderVesselMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('units', models.TextField(null=True)),
                ('crush_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crush_order_vessel_mappings', to='apps.crushorder')),
            ],
        ),
        migrations.CreateModel(
            name='Docket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docket_number', models.TextField(unique=True)),
                ('vintage', models.IntegerField(null=True)),
                ('varietal', models.TextField(null=True)),
                ('vineyard', models.TextField(null=True)),
                ('block', models.TextField(null=True)),
                ('grower', models.TextField(null=True)),
                ('crush_orders', models.ManyToManyField(through='apps.CrushOrderDocketMapping', to='apps.crushorder')),
            ],
        ),
        migrations.CreateModel(
            name='BlockChoices',
            fields=[
                ('basechoicemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apps.basechoicemodel')),
            ],
            bases=('apps.basechoicemodel',),
        ),
        migrations.CreateModel(
            name='CrushOrderTypeChoices',
            fields=[
                ('basechoicemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apps.basechoicemodel')),
            ],
            bases=('apps.basechoicemodel',),
        ),
        migrations.CreateModel(
            name='GrowerChoices',
            fields=[
                ('basechoicemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apps.basechoicemodel')),
            ],
            bases=('apps.basechoicemodel',),
        ),
        migrations.CreateModel(
            name='UnitChoices',
            fields=[
                ('basechoicemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apps.basechoicemodel')),
            ],
            bases=('apps.basechoicemodel',),
        ),
        migrations.CreateModel(
            name='VarietalChoices',
            fields=[
                ('basechoicemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apps.basechoicemodel')),
            ],
            bases=('apps.basechoicemodel',),
        ),
        migrations.CreateModel(
            name='VesselIdChoices',
            fields=[
                ('basechoicemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apps.basechoicemodel')),
            ],
            bases=('apps.basechoicemodel',),
        ),
        migrations.CreateModel(
            name='VesselTypeChoices',
            fields=[
                ('basechoicemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apps.basechoicemodel')),
            ],
            bases=('apps.basechoicemodel',),
        ),
        migrations.CreateModel(
            name='VineyardChoices',
            fields=[
                ('basechoicemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apps.basechoicemodel')),
            ],
            bases=('apps.basechoicemodel',),
        ),
        migrations.CreateModel(
            name='VintageChoices',
            fields=[
                ('basechoicemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apps.basechoicemodel')),
            ],
            bases=('apps.basechoicemodel',),
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.TextField(null=True)),
                ('type_id', models.TextField(null=True)),
                ('expansion_chamber_diameter', models.FloatField(null=True)),
                ('expansion_chamber_height', models.FloatField(null=True)),
                ('expansion_chamber_radius', models.FloatField(null=True)),
                ('tank_diameter', models.FloatField(null=True)),
                ('top_cone_height', models.FloatField(null=True)),
                ('cylinder_height', models.FloatField(null=True)),
                ('cylinder_radius', models.FloatField(null=True)),
                ('floor_height', models.FloatField(null=True)),
                ('crush_orders', models.ManyToManyField(through='apps.CrushOrderVesselMapping', to='apps.crushorder')),
            ],
        ),
        migrations.CreateModel(
            name='FruitIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 20, 18, 28, 14, 342428))),
                ('number_of_bins', models.IntegerField(null=True)),
                ('total_weight', models.IntegerField(null=True)),
                ('tare_weight', models.IntegerField(null=True)),
                ('units', models.TextField(null=True)),
                ('crush_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fruit_intakes', to='apps.crushorder')),
                ('docket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fruit_intakes', to='apps.docket')),
            ],
        ),
        migrations.AddField(
            model_name='crushordervesselmapping',
            name='vessel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crush_order_vessel_mappings', to='apps.vessel'),
        ),
        migrations.AddField(
            model_name='crushorderdocketmapping',
            name='docket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crush_order_docket_mappings', to='apps.docket'),
        ),
        migrations.AddField(
            model_name='crushorder',
            name='dockets',
            field=models.ManyToManyField(through='apps.CrushOrderDocketMapping', to='apps.docket'),
        ),
        migrations.AddField(
            model_name='crushorder',
            name='vessels',
            field=models.ManyToManyField(through='apps.CrushOrderVesselMapping', to='apps.vessel'),
        ),
    ]
